In [1]:
import pandas as pd

In [2]:
data={
    "Name" :['Ram' ,'Shyam', 'Ghanshyam'],
    "Age" :[20,23,22],
    "city":['lko','Delhi','Agra']
}

In [3]:
df=pd.DataFrame(data)

In [4]:
print(df)

        Name  Age   city
0        Ram   20    lko
1      Shyam   23  Delhi
2  Ghanshyam   22   Agra

In [7]:
df.to_csv("output.csv",index=False)

In [9]:
print(df)

        Name  Age   city
0        Ram   20    lko
1      Shyam   23  Delhi
2  Ghanshyam   22   Agra

In [1]:
import pandas as pd

df = pd.read_excel("output.xlsx")
print(df)

        Name  Age   city
0        Ram   20    lko
1      Shyam   23  Delhi
2  Ghanshyam   22   Agra

In [2]:
# head() tail()
#head(n)  n pass kenege to starting ki n row degna agr nhi pass krnege n to stating 5 row dega
#tail(n)  last ki n row similarly as head()

In [4]:
import pandas as pd

In [16]:
df=pd.read_csv(r"C:\Users\anshi\Downloads\tested-selected-columns.csv")

In [20]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875

In [18]:
print("Display 2 rows of head")
df.head(2)

Display 2 rows of head

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000

In [21]:
print("Display 2 rows of tail")
df.tail()

Display 2 rows of tail

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583