In [1]:
# 1- column no. , row no ?
# 2- what type of data ?
# 3- missing data ?

# info() --> method 

# 1- number of rows and colmn 
# 2- colmn name 
# 3- int64 float64 object
# 4- non null counts
# 5- memory usage of dataframe

In [3]:
import pandas as pd
df = pd.read_csv(r"C:\Users\anshi\Downloads\archive.zip")
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Invoice ID               1000 non-null   object
 1   Branch                   1000 non-null   object
 2   City                     1000 non-null   object
 3   Customer type            1000 non-null   object
 4   Gender                   1000 non-null   object
 5   Product line             1000 non-null   object
 6   Unit price               1000 non-null   float64
 7   Quantity                 1000 non-null   int64
 8   Tax 5%                   1000 non-null   float64
 9   Sales                    1000 non-null   float64
 10  Date                     1000 non-null   object
 11  Time                     1000 non-null   object
 12  Payment                  1000 non-null   object
 13  cogs                     1000 non-null   float64
 14  gross margin percentage  1000 non-null   float64
 15  gross income             1000 non-null   float64
 16  Rating                   1000 non-null   float64
dtypes: float64(7), int64(1), object(9)
memory usage: 132.9+ KB
None

In [6]:
df= pd.read_csv("output1.csv")
print(df)
print(df.info())
df.describe()

      name  age     city
0  Anshika   23  Lucknow
1     Neha   22   Kanpur
2    Alfee   20    Delhi
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      object
 1   age     3 non-null      int64
 2   city    3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes
None

             age
count   3.000000
mean   21.666667
std     1.527525
min    20.000000
25%    21.000000
50%    22.000000
75%    22.500000
max    23.000000

In [9]:
data = {
    "name":['Abhay','Shiva','Akanksha','Anshika'],
    "age":[20,19,25,23],
    "Salary":[700000000,5500000000,900000000,800000000],
    "Peformance Score":[100,100,100,100]
}

df = pd.DataFrame(data)
print(df)

       name  age      Salary  Peformance Score
0     Abhay   20   700000000               100
1     Shiva   19  5500000000               100
2  Akanksha   25   900000000               100
3   Anshika   23   800000000               100

In [10]:
df.describe()

             age        Salary  Peformance Score
count   4.000000  4.000000e+00               4.0
mean   21.750000  1.975000e+09             100.0
std     2.753785  2.351418e+09               0.0
min    19.000000  7.000000e+08             100.0
25%    19.750000  7.750000e+08             100.0
50%    21.500000  8.500000e+08             100.0
75%    23.500000  2.050000e+09             100.0
max    25.000000  5.500000e+09             100.0

In [11]:
df.head(2)

    name  age      Salary  Peformance Score
0  Abhay   20   700000000               100
1  Shiva   19  5500000000               100

In [12]:
df.tail(2)

       name  age     Salary  Peformance Score
2  Akanksha   25  900000000               100
3   Anshika   23  800000000               100

In [15]:
df.dtypes

name                object
age                  int64
Salary               int64
Peformance Score     int64
dtype: object

In [ ]:
    # 1-To know how big is your dataset 
    # 2-What are the name of columns 
    # Shapes and column method is provided in pandas
import pandas as pd 
data = {
    "name":['Abhay','Shiva','Akanksha','Anshika'],
    "age":[20,19,25,23],
    "Salary":[700000000,5500000000,900000000,800000000],
    "Peformance Score":[100,100,100,100]
}

df = pd.DataFrame(data)
# print(df)
print(f'Shape: {df.shape}')
print(f'Column name : {df.columns}')

 1- To select specific column 
 2- filter rows 
 3- combine with conditions 

 to solve these problems pandas give solution
 
 1- use square backets[] to select specific columns 
 2- boolean condition too filter 


selecting columns

1- a series 
2- dataFrame multiple columns data 

--> syntax 
column = df["column name "]     for particular column 
subset = df["column1","column2"]    for choosing multiple columns 


filtering rows 

1- boolean indexing 
--> filtered_Rows = df[df["salary"] > 50000]   for single condition
-->filtered_rows = df[(df["salary"] > 50000) & (df["salary"]<800000)]

In [9]:
import pandas as pd
data = {
    "name":['Abhay','Shiva','Akanksha','Anshika'],
    "age":[20,19,25,23],
    "Salary":[700000000,5500000000,900000000,800000000],
    "Peformance Score":[100,100,100,100]
}
df = pd.DataFrame(data)
# print(df)

print("Names (Single column return series)")
print(df["name"])

Names (Single column return series)
0       Abhay
1       Shiva
2    Akanksha
3     Anshika
Name: name, dtype: object

In [11]:
# selecting multiple columns 
import pandas as pd
data = {
    "name":['Abhay','Shiva','Akanksha','Anshika'],
    "age":[20,19,25,23],
    "Salary":[700000000,5500000000,900000000,800000000],
    "Peformance Score":[100,100,100,100]
}
df = pd.DataFrame(data)
print(df[["name","age"]])

       name  age
0     Abhay   20
1     Shiva   19
2  Akanksha   25
3   Anshika   23

In [21]:
  # rows filtering
import pandas as pd
data = {
    "name":['Abhay','Shiva','Akanksha','Anshika'],
    "age":[20,19,25,23],
    "Salary":[700000000,5500000000,900000000,800000000],
    "Peformance Score":[100,100,100,100]
}
df = pd.DataFrame(data)
high_salary = df[(df["Salary"]>700000000) & (df["age"]>19)]
print(high_salary)
high_salary = df[(df["Salary"]>700000000) | (df["age"]>19)]
print(high_salary)

       name  age     Salary  Peformance Score
2  Akanksha   25  900000000               100
3   Anshika   23  800000000               100
       name  age      Salary  Peformance Score
0     Abhay   20   700000000               100
1     Shiva   19  5500000000               100
2  Akanksha   25   900000000               100
3   Anshika   23   800000000               100